// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyioLd4iZ2GgyA3FQp76XbsKmlKIPFoXI',
    appId: '1:94912856667:web:3902cf7040ea38854cb57e',
    messagingSenderId: '94912856667',
    projectId: 'ramos-advmblprog',
    authDomain: 'ramos-advmblprog.firebaseapp.com',
    storageBucket: 'ramos-advmblprog.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHorHREpQ302FmxgeLrqMMkfk4B3zzMg8',
    appId: '1:94912856667:android:9b83377fa65bc4d84cb57e',
    messagingSenderId: '94912856667',
    projectId: 'ramos-advmblprog',
    storageBucket: 'ramos-advmblprog.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUZ-N5CZuMub4S_9qgjB6qjCWc8DAHw9k',
    appId: '1:94912856667:ios:0f9bd78c5d26df9a4cb57e',
    messagingSenderId: '94912856667',
    projectId: 'ramos-advmblprog',
    storageBucket: 'ramos-advmblprog.firebasestorage.app',
    iosBundleId: 'com.example.flutterConnection',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUZ-N5CZuMub4S_9qgjB6qjCWc8DAHw9k',
    appId: '1:94912856667:ios:0f9bd78c5d26df9a4cb57e',
    messagingSenderId: '94912856667',
    projectId: 'ramos-advmblprog',
    storageBucket: 'ramos-advmblprog.firebasestorage.app',
    iosBundleId: 'com.example.flutterConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyioLd4iZ2GgyA3FQp76XbsKmlKIPFoXI',
    appId: '1:94912856667:web:f3c94a49bff064bb4cb57e',
    messagingSenderId: '94912856667',
    projectId: 'ramos-advmblprog',
    authDomain: 'ramos-advmblprog.firebaseapp.com',
    storageBucket: 'ramos-advmblprog.firebasestorage.app',
  );
}
